version: '3'
services:
  dmrpp:
    # Path to dockerfile.
    # '.' represents the current directory in which
    # docker-compose.yml is present.
    build: .
    image: ghrcdaac/dmrpp-generator
    environment:
      - PAYLOAD=${PAYLOAD}
    # Mount volume
    volumes:
      - ${NC_FILES_PATH}:/usr/share/hyrax

  hyrax:

    # image to fetch from docker hub
    image: opendap/hyrax:snapshot
    ports:
    - "${PORT}:8080"
    volumes:
      - ${NC_FILES_PATH}:/usr/share/hyrax/
    working_dir: /usr/share/hyrax
    container_name: hyrax
